### ISSUE TITLE
Code Release 

### ISSUE THREAD

**Issue by aniskacem** [cfeng16/audio-visual-forensics#1]
Dear authors, 

Thank you for the excellent work! 

Could you please let us know when the codes will be released? 

Looking forward to testing the approach! 

Best,

**Comment by laiyingxin2** [comment]
when the codes will be released?

**Comment by Tea7374** [comment]
pls

**Comment by IFICL** [comment]
We are working on the code releasing, hopefully we will have it public in two weeks.

**Comment by yinghuozijin** [comment]
> We are working on the code releasing, hopefully we will have it public in two weeks.

哈哈，两周已经过去了，可以把现在已经整理的代码先上传吗，对你们的工作很感兴趣。 @IFICL

**Comment by Mrfortuante** [comment]
> We are working on the code releasing, hopefully we will have it public in two weeks.

@IFICL However, a month has passed.😅

**Comment by Mrfortuante** [comment]
> We are working on the code releasing, hopefully we will have it public in two weeks.

However, a month has passed.

**Comment by Mrfortuante** [comment]
> We are working on the code releasing, hopefully we will have it public in two weeks.
@cfeng16  @IFICL  Hi, can you give us a specific time when you will release the code?

**Comment by cfeng16** [comment]
I have updated the codebase. Please let me know if you have any questions
