### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by Mrfortuante** [cfeng16/audio-visual-forensics#2]
Thanks for releasing part of codes.
By the way, may I ask could you release the code of loading data first?
Thanks a lot.

**Comment by Mrfortuante** [comment]
Thanks, can you share the demo script?

**Comment by mowen9** [comment]
Did you obtain the code of loading data?

**Comment by Mrfortuante** [comment]
> Did you obtain the code of loading data?

@mowen9  No, the author provides very limited information.

**Comment by Mrfortuante** [comment]
@cfeng16 Hello, can you release the demo script?  Current code is too limit to re-implement. Plz.

**Comment by Mrfortuante** [comment]
I just wonder that does it really so hard to release the completed code?

**Comment by mowen9** [comment]
> I just wonder that does it really so hard to release the completed code?

I also wonder whether he will release the completed code.

**Comment by Mrfortuante** [comment]
> > I just wonder that does it really so hard to release the completed code?
> 
> I also wonder whether he will release the completed code.

@mowen9  Hi, have you try to reimplement his code?

**Comment by mowen9** [comment]
> > > I just wonder that does it really so hard to release the completed code?
> > 
> > 
> > I also wonder whether he will release the completed code.
> 
> @mowen9 Hi, have you try to reimplement his code?

Yes! However, his code contains too little information, which is not enough to reproduce the results.
There is too little publicly available code in the audio-visual deepfake detection task. This task is too difficult to perform.

**Comment by cfeng16** [comment]
I'll release them, sorry for the delay

**Comment by Mrfortuante** [comment]
> > > > I just wonder that does it really so hard to release the completed code?
> > > 
> > > 
> > > I also wonder whether he will release the completed code.
> > 
> > 
> > @mowen9 Hi, have you try to reimplement his code?
> 
> Yes! However, his code contains too little information, which is not enough to reproduce the results. There is too little publicly available code in the audio-visual deepfake detection task. This task is too difficult to perform.

1. @mowen9  Hello, maybe we can communicate by email? My email is [mrfortunate@163.com](url) , please contact me if you are interested.

**Comment by cfeng16** [comment]
I have updated the codebase. Please let me know if you have any questions
