### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by YasamanAdl94** [cfeng16/audio-visual-forensics#3]
Hello,

There is a link provided in the paper for the GitHub project however there is no code here. Can you please release the code so we can reproduce results for our research as well? Thank you.

**Comment by cfeng16** [comment]
Sure, I'll release them soon. Please stay tuned

**Comment by Mrfortuante** [comment]
> Hello,
> 
> There is a link provided in the paper for the GitHub project however there is no code here. Can you please release the code so we can reproduce results for our research as well? Thank you.

@cfeng16  Hello, thanks for your work. Can you please release a version of the code firstly, even if it's incomplete. Cause we need this for our research now. Thank you.

**Comment by cfeng16** [comment]
I have updated the codebase. Please let me know if you have any questions
