### ISSUE TITLE
Pre-trained audio and video encoders

### ISSUE THREAD

**Issue by adrianSRoman** [cfeng16/audio-visual-forensics#4]
Hi Chao, 

First of all, thank you so much for sharing your research and making the code publicly available. 

I would like to run some experiments with the model. However, I am running into problems finding the pre-trained Resnet18 2D+3D encoder, and the pre-trained VGGM audio encoder. I was wondering if you could share the pre-trained encoders? It seems like the Resnet18 you used has some slight variations compared to https://github.com/TengdaHan/DPC/blob/master/backbone/resnet_2d3d.py, and your VGGM compared to https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/vggm.py, so I want to make sure I use the right pre-trained model. Thanks in advance!

**Comment by cfeng16** [comment]
I have updated the codebase. Please let me know if you have any questions
