### ISSUE TITLE
Issue in using the model checkpoint

### ISSUE THREAD

**Issue by tusharbagwe98** [cfeng16/audio-visual-forensics#5]
Dear sir, i tried to check the pretrained model provided in the google drive , but i am facing the following issue
[error.pdf](https://github.com/cfeng16/audio-visual-forensics/files/14550147/error.pdf)
 This issue has occured when i tried to replicate the whole code in google colab and in av_sync i tried to call the model's state_dict , but it shows this error above.
Please , update if any mistake which i am doing , or the correct way to call the model.
Thank you

**Comment by cfeng16** [comment]
I have updated the codebase. Please let me know if you have any questions
