### ISSUE TITLE
Request of the training codes

### ISSUE THREAD

**Issue by WangyiNTU** [cfeng16/audio-visual-forensics#6]
Thanks for your excellent contribution and good work. I'd like to re-implement your model, but the code is incomplete. May I ask for the training codes of the "Audio-visual Synchronization Model" and "Anomaly detection model". Thanks again for your open-source spirit.

**Comment by cfeng16** [comment]
I have updated the codebase. Please let me know if you have any questions

**Comment by ucas-hao** [comment]
Will you release the training code? Thanks!

**Comment by cfeng16** [comment]
@icemoon-creative sorry at this moment i don't have much time to clean up training code, but please let me know if you have questions about training, feel free to shoot me an email chfeng@umich.edu
