### ISSUE TITLE
AP and AUC Plots 

### ISSUE THREAD

**Issue by tushar0698** [cfeng16/audio-visual-forensics#7]
Dear sir, please provide the code for AP and AUC plots.Thank you

**Comment by cfeng16** [comment]
I used sklearn for AP and AUC. I recommend you check https://scikit-learn.org/stable/modules/generated/sklearn.metrics.auc.html and https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html. let me know if you have any other questions
